#!/usr/bin/env bash

set -o errtrace
# echo control characters in hat notation ('^c')
stty -echoctl

# shellcheck disable=SC1090
source "${FABKIT_ROOT}/.env"
# shellcheck disable=SC1090
for f in "${FABKIT_ROOT}"/scripts/*; do source "$f"; done

trap '__catch $?' ERR
trap 'exit' ABRT INT TERM
trap 'kill 0' EXIT QUIT

export GO111MODULE=on
# shellcheck disable=SC2034
readonly ONE_ORG="OneOrgOrdererGenesis"
# shellcheck disable=SC2034
readonly TWO_ORGS="TwoOrgsOrdererGenesis"
# shellcheck disable=SC2034
readonly THREE_ORGS="ThreeOrgsOrdererGenesis"
# shellcheck disable=SC2034
readonly RAFT_ONE_ORG="OneOrgOrdererEtcdRaft"
# shellcheck disable=SC2034
readonly FABKIT_FABRIC_AVAILABLE_VERSIONS=("2.3.2" "2.3.1" "2.3.0" "2.3" "2.2.3" "2.2.2" "2.2.1" "2.2" "2.2.0" "2.1.0" "2.1" "2.0.1" "2.0.0" "2.0.0-alpha" "1.4" "1.4.12" "1.4.11" "1.4.10" "1.4.9" "1.4.8" "1.4.7" "1.4.6" "1.4.5" "1.4.4" "1.4.3" "1.4.2" "1.4.1" "1.4.0" "1.3.0" "1.2.1" "1.2.0" "1.1.0")
# shellcheck disable=SC2034
readonly FABKIT_DOCKER_VERSION_SUPPORTED="18.05"
# shellcheck disable=SC2034
readonly FABKIT_DOCKER_COMPOSE_VERSION_SUPPORTED="1.24"
# shellcheck disable=SC2034
readonly FABKIT_BASH_VERSION_SUPPORTED="3.2"
# shellcheck disable=SC2034
readonly FABKIT_GO_VERSION_SUPPORTED="1.11"
# shellcheck disable=SC2034
readonly FABKIT_NODE_VERSION_SUPPORTED="10.20"
# shellcheck disable=SC2034
readonly FABKIT_JAVA_VERSION_SUPPORTED="8"

export FABKIT_HOST_ROOT="${FABKIT_HOST_ROOT:-$FABKIT_ROOT}"

__log_setup() {
    loghead "\nRunning setup"
    echo "Root directory: $(loginfo ${FABKIT_HOST_ROOT})"
    echo "Docker network: $(loginfo ${FABKIT_DOCKER_NETWORK})"
    echo "Fabric version: $(loginfo ${FABKIT_FABRIC_VERSION})"
    echo "Fabric CA version: $(loginfo ${FABKIT_FABRIC_CA_VERSION})"
    echo "Fabric third-party version: $(loginfo ${FABKIT_FABRIC_THIRDPARTY_IMAGE_VERSION})"
    echo "Network configuration profile: $(loginfo ${FABKIT_CONFIGTX_PROFILE_NETWORK})"
    echo "Channel configuration profile: $(loginfo ${FABKIT_CONFIGTX_PROFILE_CHANNEL})"
    echo "Chaincode name: $(loginfo ${FABKIT_CHAINCODE_NAME})"
    echo "Chaincode version: $(loginfo ${FABKIT_CHAINCODE_VERSION})"
    echo "Organizations: $(loginfo ${FABKIT_ORGS:-1})"
    echo "TLS enabled: $(loginfo ${FABKIT_TLS_ENABLED})"
    echo "Debug mode: $(loginfo ${FABKIT_DEBUG:-false})"
    echo "Reset mode: $(loginfo ${FABKIT_RESET:-false})"
    echo "Quick-run mode: $(loginfo ${FABKIT_QUICK_RUN:-false})"
    echo "Interactive mode: $(loginfo ${FABKIT_INTERACTIVE:-false})"
    echo
}

__yq() {
    if type -p yq &>/dev/null; then
        yq "$@"
    else
        docker run --rm -i -v "${PWD}":/workdir "$FABKIT_YQ_DOCKER_IMAGE" "$@"
    fi
}

__jq() {
    if type -p jq &>/dev/null; then
        jq "$@"
    else
        docker run --rm -i -v "${PWD}":/workdir "$FABKIT_JQ_DOCKER_IMAGE" "$@"
    fi
}

__set_params() {
    if [ $# -eq 0 ]; then
        __load_lastrun
        return 0
    fi

    while [ $# -gt 0 ]; do
        local param="$1"

        case $param in
        -q | --quick-run)
            export FABKIT_QUICK_RUN=true
            shift
            ;;
        -d | --debug)
            export FABKIT_DEBUG=true
            shift
            ;;
        -r | --reset)
            export FABKIT_RESET=true
            __clean_user_path
            shift
            ;;
        -i | --interactive)
            # TODO: [FND-117] implement support for interactive mode (now set to false)
            logwarn "Interactive mode is not supported yet, sorry 😔"
            export FABKIT_INTERACTIVE=false
            shift
            ;;
        -o | --orgs)
            export FABKIT_ORGS="${2:-1}"
            shift 2
            ;;
        -v | --version)
            export FABKIT_FABRIC_VERSION="${2:-$FABKIT_FABRIC_VERSION}"
            shift 2
            ;;
        help)
            help_network
            exit 1
            ;;
        *)
            logerr "${1} paramater not recognized. Please run the help."
            exit 1
            ;;
        esac
    done
}

__set_debug() {
    for param in "$@"; do
        case $param in
        -d | --debug)
            export FABKIT_DEBUG=true
            ;;
        esac
    done
}

readonly FUNC="$1"
if [ -z "$FUNC" ]; then
    title
    help
    exit
elif [ "$FUNC" = "version" ]; then
    echo "$FABKIT_VERSION"
    exit
fi

readonly START_TIME="$(date -u +%s)"
title
__check_dep_version
__set_debug "$@"

shift || true
if [ "$FUNC" = "network" ]; then
    PARAM="$1"
    shift || true
    __set_params "$@"
    __validate_params
    if [ "$PARAM" = "install" ]; then
        __log_setup
        install_network
    elif [ "$PARAM" = "start" ]; then
        start_network "$@"
    elif [ "$PARAM" = "restart" ]; then
        restart_network
    elif [ "$PARAM" = "stop" ]; then
        __load_lastrun
        __log_setup
        (stop_network) &
        __spinner
    else
        help_network
        exit
    fi
elif [ "$FUNC" = "explorer" ]; then
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "start" ]; then
        start_explorer
    elif [ "$PARAM" = "stop" ]; then
        (stop_explorer) &
        __spinner
    else
        help_explorer
        exit
    fi
elif [ "$FUNC" = "dep" ]; then
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "install" ]; then
        (dep_install "$@") &
        __spinner
    elif [ "$PARAM" = "update" ]; then
        (dep_update "$@") &
        __spinner
    else
        help_dep
        exit
    fi
elif [ "$FUNC" = "chaincode" ]; then
    __load_lastrun
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "lifecycle" ]; then
        __check_fabric_version 2
        PARAM="$1"
        shift || true
        if [ "$PARAM" = "package" ]; then
            (lifecycle_chaincode_package "$@") &
            __spinner
        elif [ "$PARAM" = "install" ]; then
            (lifecycle_chaincode_install "$@") &
            __spinner
        elif [ "$PARAM" = "approve" ]; then
            (lifecycle_chaincode_approve "$@") &
            __spinner
        elif [ "$PARAM" = "commit" ]; then
            (lifecycle_chaincode_commit "$@") &
            __spinner
        elif [ "$PARAM" = "deploy" ]; then
            lifecycle_chaincode_deploy "$@"
        else
            help_chaincode
            exit
        fi
    elif [ "$PARAM" = "install" ]; then
        (chaincode_install "$@") &
        __spinner
    elif [ "$PARAM" = "instantiate" ]; then
        (chaincode_instantiate "$@") &
        __spinner
    elif [ "$PARAM" = "upgrade" ]; then
        (chaincode_upgrade "$@") &
        __spinner
    elif [ "$PARAM" = "test" ]; then
        (chaincode_test "$@") &
        __spinner
    elif [ "$PARAM" = "build" ]; then
        (chaincode_build "$@") &
        __spinner
    elif [ "$PARAM" = "package" ]; then
        (chaincode_pack "$@") &
        __spinner
    elif [ "$PARAM" = "zip" ]; then
        (chaincode_zip "$@") &
        __spinner
    elif [ "$PARAM" = "query" ]; then
        (chaincode_query "$@") &
        __spinner
    elif [ "$PARAM" = "invoke" ]; then
        (chaincode_invoke "$@") &
        __spinner
    else
        help_chaincode
        exit
    fi
elif [ "$FUNC" = "generate" ]; then
    PARAM="${1}"
    shift || true
    if [ "$PARAM" = "cryptos" ]; then
        generate_cryptos "$@"
    elif [ "$PARAM" = "genesis" ]; then
        generate_genesis "$@"
    elif [ "$PARAM" = "channeltx" ]; then
        generate_channeltx "$@"
    else
        help_generate
        exit
    fi
elif [ "$FUNC" = "ca" ]; then
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "register" ]; then
        register_user "$@"
    elif [ "$PARAM" = "enroll" ]; then
        enroll_user "$@"
    elif [ "$PARAM" = "reenroll" ]; then
        reenroll_user "$@"
    elif [ "$PARAM" = "revoke" ]; then
        revoke_user "$@"
    else
        help_ca
        exit
    fi
elif [ "$FUNC" = "channel" ]; then
    PARAM="$1"
    __load_lastrun
    shift || true
    if [ "$PARAM" = "create" ]; then
        (init_and_create_channel "$@") &
        __spinner
    elif [ "$PARAM" = "update" ]; then
        (update_channel "$@") &
        __spinner
    elif [ "$PARAM" = "join" ]; then
        (join_channel "$@") &
        __spinner
    else
        help_channel
        exit
    fi
elif [ "$FUNC" = "benchmark" ]; then
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "load" ]; then
        (__exec_jobs "$@") &
        __spinner
    else
        help_benchmark
        exit
    fi
elif [ "$FUNC" = "utils" ]; then
    PARAM="$1"
    shift || true
    if [ "$PARAM" = "tostring" ]; then
        tostring "$@"
    elif [ "$PARAM" = "tojson" ]; then
        tojson "$@"
    else
        help_utils
        exit
    fi
elif [ "$FUNC" = "install" ]; then
    __set_params "$@"
    __validate_params
    __log_setup
    install_network
elif [ "$FUNC" = "start" ]; then
    __set_params "$@"
    __validate_params
    start_network "$@"
elif [ "$FUNC" = "restart" ]; then
    __set_params "$@"
    __validate_params
    __load_lastrun
    __log_setup
    __check_previous_network
elif [ "$FUNC" = "stop" ]; then
    __set_params "$@"
    __validate_params
    __load_lastrun
    __log_setup
    __check_docker_volumes
else
    help
    exit
fi

readonly END_TIME="$(date -u +%s)"
__timer "$START_TIME" "$END_TIME"
